extends RefCounted

const FOUNDATION_VERSION: String = "0.16.0-dev"
const GODOT_BASELINE: String = "4.7.2"


static func info() -> Dictionary:
	return {
		"name": "Godot Game Foundation",
		"foundation_version": FOUNDATION_VERSION,
		"godot_baseline": GODOT_BASELINE,
	}


static func capabilities() -> PackedStringArray:
	return PackedStringArray([
		"foundation_core",
		"generic_save_system",
		"save_versioning",
		"atomic_save",
		"backup_recovery",
		"migration_hook",
		"autosave_api",
		"save_slot_manager",
		"save_slot_metadata",
		"continue_latest_slot",
		"new_game_slot_helper",
		"settings_system",
		"locale_setting_adapter",
		"translation_contract",
		"audio_settings",
		"audio_bus_contract",
		"global_music_service",
		"one_shot_audio_service",
		"display_settings",
		"gameplay_settings_extension",
		"settings_persistence",
		"settings_edit_session",
		"generic_option_controls",
		"input_system",
		"input_rebind",
		"input_remap_ui",
		"input_conflict_detection",
		"input_prompt_resolver",
		"input_persistence",
		"keyboard_mouse_bindings",
		"gamepad_binding_model",
		"game_flow",
		"pause_service",
		"scene_contract",
		"main_menu_contract",
		"safe_quit_hooks",
		"diagnostics",
		"diagnostics_export_hook",
		"runtime_version_info",
		"log_service",
		"debug_overlay",
		"error_summary",
		"windows_build",
		"windows_export_preset",
		"ci_export_artifact",
		"build_metadata",
		"starter_template",
		"managed_foundation_distribution",
		"integrated_foundation_runtime",
		"runtime_failure_state",
		"recovery_screen_contract",
		"crash_marker",
		"runtime_lifecycle_bootstrap",
		"runtime_test_bridge",
		"application_shell",
		"transition_layer",
		"async_scene_loader",
		"loading_screen_contract",
		"main_menu_shell",
		"menu_focus_navigation",
		"focus_navigation_baseline",
		"ui_feedback_hooks",
		"pause_menu_shell",
	])
